services:
  - type: web
    name: manhaj-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 bot.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.2
